### ISSUE TITLE
publish the game on gh-pages with peanut

### ISSUE THREAD

**Issue by kevmoo** [dzenanr/order#1]
https://pub.dartlang.org/packages/peanut

Then add a link to the branch in the site description so it's easy to play

**Comment by dzenanr** [comment]
I have added the following 2 paths to the path environment variable on Windows:

C:\Users\ridjanod.FSA-RIDJANOD-2\AppData\Roaming\Pub\Cache\bin;
C:\Users\ridjanod.FSA-RIDJANOD-2\darteditor-windows-x64\dart\dart-sdk\bin

Then I have activated peanut:

cd "C:\Users\ridjanod.FSA-RIDJANOD-2\Google Drive\learningdart\app\order"
C:\Users\ridjanod.FSA-RIDJANOD-2\Google Drive\learningdart\app\order>pub global activate
peanut

However, when I run peanut,

cd "C:\Users\ridjanod.FSA-RIDJANOD-2\Google Drive\learningdart\app\order"
C:\Users\ridjanod.FSA-RIDJANOD-2\Google Drive\learningdart\app\order>peanut

I get the following error:

Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\ridjanod.FSA-RIDJANOD-2>cd "C:\Users\ridjanod.FSA-RIDJANOD-2\Google Dri
ve\learningdart\app\order"

C:\Users\ridjanod.FSA-RIDJANOD-2\Google Drive\learningdart\app\order>peanut
Unhandled exception:
Uncaught Error: ProcessException: Le fichier sp├®cifi├® est introuvable.

  Command: git rev-parse
Stack Trace:
#0      GitDir._isGitDir.<_isGitDir_async_body> (package:git/src/git_dir.dart)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:1
5)
#2      _RootZone.runBinary (dart:async/zone.dart:1160)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:5
11)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#5      _Future._completeError (dart:async/future_impl.dart:366)
#6      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.
dart:421)
#7      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#8      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:392)
#11     _handleMessage (dart:isolate-patch/timer_impl.dart:411)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:142)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:392)
#5      _handleMessage (dart:isolate-patch/timer_impl.dart:411)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:142)
Unhandled exception:
Uncaught Error: ProcessException: Le fichier sp├®cifi├® est introuvable.

  Command: git rev-parse
Stack Trace:
#0      GitDir._isGitDir.<_isGitDir_async_body> (package:git/src/git_dir.dart)
#1      _asyncCatchHelper.<anonymous closure> (dart:core-patch/core_patch.dart:1
5)
#2      _RootZone.runBinary (dart:async/zone.dart:1160)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:5
11)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#5      _Future._completeError (dart:async/future_impl.dart:366)
#6      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.
dart:421)
#7      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#8      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:392)
#11     _handleMessage (dart:isolate-patch/timer_impl.dart:411)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:142)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:392)
#5      _handleMessage (dart:isolate-patch/timer_impl.dart:411)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:142)

C:\Users\ridjanod.FSA-RIDJANOD-2\Google Drive\learningdart\app\order>

**Comment by kevmoo** [comment]
I'm not good at french

`sp├®cifi├®` does this refer to a file in your project somewhere?

**Comment by dzenanr** [comment]
It means: 
The specified file cannot be found.

**Comment by dzenanr** [comment]
I have moved the order project outside the Google drive:

cd C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\order
C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\order>peanut

However, I get the same error.

**Comment by kevmoo** [comment]
Does it say which file is not found?

**Comment by kevmoo** [comment]
Ah! Is the directory already a git repository?

**Comment by kevmoo** [comment]
...and is `git` on your path?

**Comment by dzenanr** [comment]
It is already a git repository and git is on the path:

"C:\Program Files (x86)\Git\bin";

**Comment by kevmoo** [comment]
Hmm... Okay. Let me look...

**Comment by dzenanr** [comment]
I am not sure what file was not found.

C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\order>peanut>peanut
Unhandled exception:
Uncaught Error: ProcessException: The specified file was not found.

Command: git rev-parse
Stack Trace:
...

**Comment by kevmoo** [comment]
I think `git` is not found. I may need to make sure I pass in the local environment.

**Comment by dzenanr** [comment]
I use a GitHub (development) version of boarding regularly from Dart Editor:

dependencies:
  boarding:
    git: https://github.com/dzenanr/boarding.git

and Dart Editor finds the git software based on the path.

**Comment by kevmoo** [comment]
Try running `pub global activate peanut` again.

I did some tweaks to the `git` package. At least we'll get better errors out – I hope.

**Comment by dzenanr** [comment]
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\ridjanod.FSA-RIDJANOD-2>cd C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\o
rder

C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\order>pub global activate peanut
Package peanut is currently active at version 0.0.1+1.
Resolving dependencies...
- args 0.13.0
- bot 0.28.0
- git 0.4.4
- path 1.3.5
- peanut 0.0.1+1
- when 0.2.0
- which 0.1.3
  Downloading git 0.4.4...
  Downloading which 0.1.3...
  Downloading when 0.2.0...
  Precompiling executables...
  Loading source assets...
  Precompiled peanut:peanut.
  Activated peanut 0.0.1+1.
  Installed executable peanut.

C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\order>peanut
Unhandled exception:
Uncaught Error: Bad state: Command not found: git
Bad state: Command not found: git
Stack Trace:
#0      _commandNotFound (package:which/src/which_impl.dart:51)
#1      _which.<anonymous closure> (package:which/src/which_impl.dart:46)
#2      _RootZone.runUnary (dart:async/zone.dart:1155)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:5
15)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#5      _completeError (dart:async/future_impl.dart:366)
#6      _runUserCode (dart:async/stream_pipe.dart:16)
#7      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1042)
#8      _RootZone.runGuarded (dart:async/zone.dart:1082)
#9      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.
dart:390)
#10     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)

#11     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#12     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/s
tream_controller.dart:706)
#13     _StreamController._closeUnchecked (dart:async/stream_controller.dart:559
)
#14     close (dart:async/stream_controller.dart:552)
#15     _RootZone.runGuarded (dart:async/zone.dart:1082)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.
dart:390)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)

#18     _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:552)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart
:671)
#20     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#21     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:143)
Unhandled exception:
Uncaught Error: Bad state: Command not found: git
Bad state: Command not found: git
Stack Trace:
#0      _commandNotFound (package:which/src/which_impl.dart:51)
#1      _which.<anonymous closure> (package:which/src/which_impl.dart:46)
#2      _RootZone.runUnary (dart:async/zone.dart:1155)
#3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:5
15)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:570)
#5      _completeError (dart:async/future_impl.dart:366)
#6      _runUserCode (dart:async/stream_pipe.dart:16)
#7      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1042)
#8      _RootZone.runGuarded (dart:async/zone.dart:1082)
#9      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.
dart:390)
#10     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)

#11     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:290)
#12     _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/s
tream_controller.dart:706)
#13     _StreamController._closeUnchecked (dart:async/stream_controller.dart:559
)
#14     close (dart:async/stream_controller.dart:552)
#15     _RootZone.runGuarded (dart:async/zone.dart:1082)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.
dart:390)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399)

#18     _IterablePendingEvents.handleNext (dart:async/stream_impl.dart:552)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart
:671)
#20     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#21     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:143)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:143)

C:\Users\ridjanod.FSA-RIDJANOD-2\dart\game\order>

**Comment by kevmoo** [comment]
On more time `pub global activate peanut`.

Then run it again...

You should see `git 0.4.4+1`

**Comment by dzenanr** [comment]
It works! Thanks.

**Comment by kevmoo** [comment]
Thank you! This is now fixed for Windows, too.

Let me know once you get your gh-pages published.

**Comment by dzenanr** [comment]
I have done:

> git update-ref refs/heads/gh-pages origin/gh-pages

Now, I am not sure what link to include in index.html of http://dzenanr.github.io/order/ ?

**Comment by dzenanr** [comment]
This one https://github.com/dzenanr/order/tree/gh-pages ?
